# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bda0d62f4baeb19b839466fff4533a16"
name = "Product Visibility Manager"
application_url = "https://miles-expenditures-fairfield-logs.trycloudflare.com"
embedded = true
handle = "product-visibility-manager"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = ["https://miles-expenditures-fairfield-logs.trycloudflare.com/auth/callback", "https://miles-expenditures-fairfield-logs.trycloudflare.com/auth/shopify/callback", "https://miles-expenditures-fairfield-logs.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
